### PR TITLE
Add endpoint for creating searches

### PR DESCRIPTION
**Pull request by fabubaker**
The request prompts the user for the pre-signed URL UUID and filename to send the request.

### CODE REVIEW

**Comment by fabubaker** [comment]
@hammady I tried parsing the UUID from the `Searches Pre-Signed URL` request, but JSONPath in Insomnia doesn't support post-processing, so I couldn't extract it and reuse it in this request. Using a user prompt seemed like the next best option.

**Comment by hammady** [comment]
> @hammady I tried parsing the UUID from the `Searches Pre-Signed URL` request, but JSONPath in Insomnia doesn't support post-processing, so I couldn't extract it and reuse it in this request. Using a user prompt seemed like the next best option.

My concern is that the process is not smooth. Typically it is a three-step process: get a pre-signed URL, upload to S3 and finally creating the search on Rayyan. We are only doing two here. What about inserting a S3 upload endpoint that gets its URL and form data from the first endpoint, and uploads a trivial file whose content is a static string? This will enable us to read the `s3_key` from its response and chain it into the third endpoint. For the `original_filename` we can use a static file name.

**Comment by fabubaker** [comment]
> > @hammady I tried parsing the UUID from the `Searches Pre-Signed URL` request, but JSONPath in Insomnia doesn't support post-processing, so I couldn't extract it and reuse it in this request. Using a user prompt seemed like the next best option.
> 
> My concern is that the process is not smooth. Typically it is a three-step process: get a pre-signed URL, upload to S3 and finally create the search on Rayyan. We are only doing two here. What about inserting an S3 upload endpoint that gets its URL and form data from the first endpoint, and uploads a trivial file whose content is a static string? This will enable us to read the `s3_key` from its response and chain it into the third endpoint. For the `original_filename` we can use a static file name.

Yeah this should do the job. What's nice is that Insomnia allows you to upload files as part of the multipart-form body, so no need for a dummy file. Can't do much about `original_filename` though.

**Review by hammady — APPROVED** [review]
I am approving this but please don't merge yet because the pre-signed URL response has changed in AWS SDK v3 since v1. All work is done, it just needs to be merged.

**Comment by hammady** [comment]
> I am approving this but please don't merge yet because the pre-signed URL response has changed in AWS SDK v3 since v1. All work is done, it just needs to be merged.

@fabubaker How about sending the whole response from the pre-signed URL endpoint to S3 so that it is compatible with all versions? Not sure if this is possible if you have to send the request in `x-www-form-urlencoded` format.

**Comment by fabubaker** [comment]
> @fabubaker How about sending the whole response from the pre-signed URL endpoint to S3 so that it is compatible with all versions? Not sure if this is possible if you have to send the request in `x-www-form-urlencoded` format.

I tried sending the request body as JSON and it returned an HTTP 412 error. I think the endpoint requires the body to be in a multipart form.

**Pull request merged**
